CREATE TABLE planos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR(20) NOT NULL UNIQUE,
                        preco_mensal DECIMAL(10,2),
                        preco_anual DECIMAL(10,2),
                        comissao_percentual DECIMAL(5,2) NOT NULL,
                        limite_agendamentos_mes INTEGER
);

CREATE TABLE assinaturas (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             prestador_id BIGINT NOT NULL REFERENCES prestadores(id) ON DELETE CASCADE,
                             plano_id BIGINT NOT NULL REFERENCES planos(id),
                             status VARCHAR(20) NOT NULL,
                             data_inicio TIMESTAMP NOT NULL,
                             data_fim TIMESTAMP NOT NULL,
                             anos_fidelidade INTEGER DEFAULT 0,
                             trial_utilizado BOOLEAN DEFAULT FALSE,

                             CONSTRAINT ck_assinatura_status
                                 CHECK (status IN ('PENDENTE', 'TRIAL', 'ATIVA', 'EXPIRADA', 'CANCELADA'))
);

CREATE INDEX idx_assinatura_prestador ON assinaturas(prestador_id);
CREATE INDEX idx_assinatura_status ON assinaturas(status);

CREATE TABLE missoes_prestador (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   prestador_id BIGINT NOT NULL REFERENCES prestadores(id) ON DELETE CASCADE,
                                   missao_tipo VARCHAR(50) NOT NULL,
                                   concluida_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   dias_bonus INTEGER NOT NULL,

                                   UNIQUE (prestador_id, missao_tipo)
);

CREATE INDEX idx_missao_prestador ON missoes_prestador(prestador_id);

INSERT INTO planos (nome, preco_mensal, preco_anual, comissao_percentual, limite_agendamentos_mes)
VALUES
    ('FREE', 0.00, 0.00, 15.00, 10),
    ('PRO_MENSAL', 49.90, NULL, 5.00, NULL),
    ('PRO_ANUAL', NULL, 499.00, 5.00, NULL);

COMMENT ON TABLE planos IS 'Planos de assinatura disponíveis para prestadores';
COMMENT ON TABLE assinaturas IS 'Assinaturas ativas dos prestadores';
COMMENT ON TABLE missoes_prestador IS 'Missões de gamificação concluídas';

COMMENT ON COLUMN planos.limite_agendamentos_mes IS 'NULL = ilimitado';
COMMENT ON COLUMN assinaturas.trial_utilizado IS 'Se já utilizou o trial de 60 dias';
COMMENT ON COLUMN missoes_prestador.dias_bonus IS 'Dias adicionados ao completar a missão';
